export const FORCE_END = 'FORCE_END';
export const GAME_STARTED = 'GAME_STARTED';
export const INITIALIZE = 'INITIALIZE';
export const PLAYER_READY = 'PLAYER_READY';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SET_LYNCH_VOTE = 'SET_LYNCH_VOTE';
export const SET_GUILTY_VOTE = 'SET_GUILTY_VOTE';
export const SET_ACTION_TARGET = 'SET_ACTION_TARGET';

export default {
  FORCE_END,
  GAME_STARTED,
  INITIALIZE,
  PLAYER_READY,
  SEND_MESSAGE,
  SET_LYNCH_VOTE,
  SET_GUILTY_VOTE,
  SET_ACTION_TARGET
};
